---- core master tables ─────────────────────────────────────────

CREATE TABLE item (
  item_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
              CONSTRAINT item_pk PRIMARY KEY,
  name        VARCHAR2(100)   NOT NULL,
  item_type   VARCHAR2(30)    NOT NULL,
  price       NUMBER(10,2)    NOT NULL,
  stock_qty   NUMBER(10)      DEFAULT 0 NOT NULL,
  CONSTRAINT item_ck_type
    CHECK (item_type IN ('FOOD','DRINK','SERVICE','OTHER'))
);

CREATE TABLE combo (
  combo_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
              CONSTRAINT combo_pk PRIMARY KEY,
  name        VARCHAR2(100)   NOT NULL,
  price       NUMBER(10,2)    NOT NULL       -- ► override auto-sum for promos
);

CREATE TABLE combo_item (
  combo_id    NUMBER NOT NULL
              CONSTRAINT combo_item_fk_combo
              REFERENCES combo (combo_id) ON DELETE CASCADE,
  item_id     NUMBER NOT NULL
              CONSTRAINT combo_item_fk_item
              REFERENCES item  (item_id)  ON DELETE CASCADE,
  quantity    NUMBER(10)      NOT NULL,
  CONSTRAINT  combo_item_pk PRIMARY KEY (combo_id, item_id)
);

---- sales & sale lines ─────────────────────────────────────────

CREATE TABLE sale (
  sale_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
              CONSTRAINT sale_pk PRIMARY KEY,
  sale_date   DATE DEFAULT SYSDATE
);

CREATE TABLE sale_line (
  sale_line_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
               CONSTRAINT sale_line_pk PRIMARY KEY,
  sale_id      NUMBER NOT NULL
               CONSTRAINT sale_line_fk_sale
               REFERENCES sale(sale_id) ON DELETE CASCADE,
  item_id      NUMBER      NULL
               CONSTRAINT sale_line_fk_item
               REFERENCES item(item_id),
  combo_id     NUMBER      NULL
               CONSTRAINT sale_line_fk_combo
               REFERENCES combo(combo_id),
  quantity     NUMBER(10)  NOT NULL,
  line_total   NUMBER(12,2)    NOT NULL,
  CONSTRAINT sale_line_ck_one_only
    CHECK (  (item_id  IS NOT NULL AND combo_id IS NULL)
          OR (item_id  IS NULL     AND combo_id IS NOT NULL) )
);

CREATE INDEX sale_line_idx_sale ON sale_line(sale_id);
